rest api for product d
MirceaDumitrescu/angular-commerce pull request #12
Opened 2023-06-01 15:11 UTC by Hionel

2023-06-07 07:12 UTC, MirceaDumitrescu requested changes

2023-06-07 07:12 UTC, MirceaDumitrescu commented on backend/controllers/auth-controller.ts
> +    const sessionTime = 3600;
```suggestion
    const SESSION_DURATION = 3600;
```

2023-06-07 07:12 UTC, MirceaDumitrescu commented on backend/controllers/auth-controller.ts
> +    const secretKey = 'Very-secret-key';
Adauga asta in .env

2023-06-07 07:12 UTC, MirceaDumitrescu commented on backend/controllers/product-controller.ts
> +const postProduct = async (req: Request, res: Response) => {
```suggestion
const addProduct = async (req: Request, res: Response) => {
```

2023-06-07 07:12 UTC, MirceaDumitrescu commented on backend/controllers/product-controller.ts
> +    !productData.title ||
Nu avem nevoie de toate verificarile astea pe backend, le facem pe frontend form validation

2023-06-07 07:12 UTC, MirceaDumitrescu commented on backend/controllers/product-controller.ts
> +    !productData.title ||
Sau poti adauga JOI schema validation

2023-06-08 10:04 UTC, MirceaDumitrescu approved these changes, later dismissed

2023-06-08 10:12 UTC, MirceaDumitrescu approved these changes

2023-06-08 10:14 UTC, CalinFlorinTUDOR approved these changes

2023-06-08 10:14 UTC, merged